"""
Context processors for AgriScan+ to make user role information
available in all templates.
kapag may request,di na need pa i pass sa bawat view ang role info.

Usage in templates:
    {% if user_role == 'admin' %}
        <!-- Admin-only content -->
    {% endif %}
    
    {% if is_admin %}
        <!-- Admin-only content -->
    {% endif %}
"""
from .services import UNKNOWN_LABEL

def user_role_processor(request):
    """
    Add user role information to template context.
    
    Available in all templates:
        - user_role: String ('farmer', 'technician', 'admin', or None)
        - is_farmer: Boolean
        - is_technician: Boolean  
        - is_admin: Boolean
    """
    if not request.user.is_authenticated:
        return {
            'user_role': None,
            'is_farmer': False,
            'is_technician': False,
            'is_admin': False,
            'UNKNOWN_LABEL': UNKNOWN_LABEL,
        }
    
    profile = getattr(request.user, 'profile', None)
    role = profile.role if profile else None
    
    return {
        'user_role': role,
        'is_farmer': role == 'farmer',
        'is_technician': role == 'technician',
        'is_admin': role == 'admin',
        'UNKNOWN_LABEL': UNKNOWN_LABEL,   # "Unknown/Not Rice" — single source of truth
    }


def announcements_processor(request):
    """
    Add unread announcements count to template context (NO INTERNET REQUIRED).
    
    Makes notification badge available in all templates:
        - unread_announcements_count: Integer count of unread announcements
    
    Used in navbar to show notification bell badge.
    """
    if not request.user.is_authenticated:
        return {'unread_announcements_count': 0}
    
    profile = getattr(request.user, 'profile', None)
    if not profile:
        return {'unread_announcements_count': 0}
    
    try:
        from . import services
        count = services.get_unread_announcements_count(profile)
        return {'unread_announcements_count': count}
    except Exception:
        # Fail silently if announcements table doesn't exist yet (before migration)
        return {'unread_announcements_count': 0}


def system_notifications_processor(request):
    """
    Add unread system Notification count to template context.

    System notifications are auto-generated by the server when:
    - A disease is detected on a scan
    - A yield drop is predicted vs historical baseline
    - A new Advisory is published by DA officers

    Makes the notification badge available in all templates:
        - unread_notifications_count: Integer (unread system notifications)

    Used in navbar to show a separate alert badge for system events.
    """
    if not request.user.is_authenticated:
        return {'unread_notifications_count': 0}

    profile = getattr(request.user, 'profile', None)
    if not profile:
        return {'unread_notifications_count': 0}

    try:
        from .models import Notification
        count = Notification.objects.filter(recipient=profile, is_read=False).count()
        return {'unread_notifications_count': count}
    except Exception:
        # Fail silently if table doesn't exist yet (before migration)
        return {'unread_notifications_count': 0}

