"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*68$rb%vg-qp46xhn+b22mr#_qo$8ga41pl^8+p1=d5fk+gqft'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local apps
    'polls.apps.PollsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'polls.context_processors.user_role_processor',  # Role-based access in templates
                'polls.context_processors.announcements_processor',  # Unread announcements count
                'polls.context_processors.system_notifications_processor',  # Unread system notifications (disease/yield/advisory)
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'agriscan_db',
        'USER': 'root',  # corrected key from USERNAME to USER
        'PASSWORD': '',
        'PORT': '3306',
        'HOST': 'localhost',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # Removed UserAttributeSimilarityValidator - allows passwords similar to user info
    # Removed CommonPasswordValidator - allows common passwords
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = False  # AgriScan is English-only; disabling avoids unnecessary translation overhead

USE_TZ = True  # Always True — stores datetimes as UTC in DB, converts to Asia/Manila for display


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media uploads (for images captured in detections)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# App-specific defaults
# ---------------------------------------------------------------------------
# These are the recommended system settings used throughout the app.
# Admin can override them via the web UI (System Settings).
SYSTEM_SETTING_DEFAULTS = {
    "allowed_past_days_planting": 30,
    "detection_confidence_threshold": 75,
}

# ============================================================================
# EMAIL CONFIGURATION (Gmail SMTP)
# Sends real-time alerts for: disease detection, yield drop, new advisories
#
# SETUP (one-time):
# 1. Go to https://myaccount.google.com/apppasswords
# 2. Create an App Password for "Mail" + "Windows Computer"
# 3. Paste the 16-character app password below (no spaces)
# 4. Set EMAIL_ENABLED = True when ready to send
# ============================================================================

EMAIL_BACKEND      = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST         = 'smtp.gmail.com'
EMAIL_PORT         = 587
EMAIL_USE_TLS      = True
EMAIL_HOST_USER    = 'jhonvincenthernandez9@gmail.com'   # sender Gmail address
EMAIL_HOST_PASSWORD = 'jnkx scjb uyhu wwlk'   # <-- paste your 16-char Gmail App Password here
DEFAULT_FROM_EMAIL = 'AgriScan+ <jhonvincenthernandez1@gmail.com>'

# Set to True only after EMAIL_HOST_PASSWORD is filled in
EMAIL_ENABLED = True

