# Generated by Django 5.2.8 on 2026-03-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_knowledgebaseentry_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was archived', null=True),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was archived', null=True),
        ),
        migrations.AddField(
            model_name='plantingrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was archived', null=True),
        ),
        migrations.AddField(
            model_name='ricevariety',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was archived', null=True),
        ),
        migrations.AddField(
            model_name='yieldprediction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was archived', null=True),
        ),
    ]
