# Generated by Django 5.2.8 on 2026-03-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_field_deleted_at_harvestrecord_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was archived', null=True),
        ),
    ]
