# Generated by Django 5.2.8 on 2026-03-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_detectionrecord_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was archived', null=True),
        ),
        migrations.AddField(
            model_name='seasonlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was archived', null=True),
        ),
        migrations.AddField(
            model_name='sitesettingaudit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was archived', null=True),
        ),
        migrations.AddField(
            model_name='treatmentrecommendation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was archived', null=True),
        ),
    ]
