# Generated by Django 5.2.8 on 2026-04-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_sitesetting_yield_cnn_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='Enable or disable outgoing email notifications globally. SMTP credentials are still read from environment variables.'),
        ),
    ]
