# Generated by Django 5.2.8 on 2026-09-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_plantingrecord_cropping_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrecord',
            name='treatment_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ricevariety',
            name='variety_type',
            field=models.CharField(choices=[('inbred', 'Inbred'), ('hybrid', 'Hybrid'), ('traditional', 'Traditional / Local')], default='inbred', help_text='Uri ng variety: Inbred, Hybrid, Traditional, Specialty, o Stress-Tolerant', max_length=12),
        ),
    ]
