# Generated by Django 5.2.8 on 2026-09-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_detectionrecord_treatment_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='publishing_mode',
            field=models.CharField(choices=[('immediate', 'Immediate Publish'), ('scheduled', 'Scheduled Publish')], db_index=True, default='immediate', help_text='Records whether the announcement was published immediately or scheduled for a future date.', max_length=20),
        ),
    ]
