# Generated by Django 5.2.8 on 2026-09-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_announcement_publishing_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='ecosystem_type',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('irrigated', 'Irrigated'), ('rainfed_lowland', 'Rainfed Lowland'), ('upland', 'Upland'), ('saline', 'Saline / Coastal'), ('other', 'Other')], help_text='Ecosystem classification for this field', max_length=50, null=True),
        ),
    ]
