# Generated by Django 5.2.8 on 2026-09-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_field_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingrecord',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='polls.field'),
        ),
    ]
