# Generated by Django 5.2.8 on 2026-09-30 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_plantingrecord_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrecord',
            name='planting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_record', to='polls.plantingrecord'),
        ),
    ]
